return {
    Sounds = {
        FISH_SPAWN = "rbxassetid://2539296793",
        FISH_DEATH = "rbxassetid://3853659609",
        FISH_EAT = "rbxassetid://9114890978",
        FISH_COIN = "rbxassetid://6817149233",
        GACHA_ROLL = "rbxassetid://4611822112",
        GACHA_WIN = "rbxassetid://1846266692",
        BUTTON_CLICK = "rbxassetid://6042053626",
        OPEN_AQUARIUM = "rbxassetid://17208204604",
        DEFAULT_BACKGROUND = "rbxassetid://119240016269232",
        BUBBLE = "rbxassetid://5217769815",
        BOSS_CLICK = "rbxassetid://6323775059",
        BOSS_WARNING = "rbxassetid://7084812679",
        BOSS_FIGHTING = "rbxassetid://1839549376",
        BOSS_EAT = "rbxassetid://625712280",
        BOSS_SPAWN = "rbxassetid://9114038441",
        BONUS_TIME_CD = "rbxassetid://6238869231",
        BONUS_TIME = "rbxassetid://1847548665",
        BONUS_CLICK = "rbxassetid://18913132985",
        BONUS_CLICK_EGG = "rbxassetid://289824844",
        BONUS_RESULT = "rbxassetid://5425356610",
        FOOD_DROP = "rbxassetid://3773015931",
    },

    Images = {
        -- UI Core
        DEFAULT_BACKGROUND = "rbxassetid://10672535737",
        Menu_ico = "rbxassetid://79113340093791",
        Admin_ico = "rbxassetid://80033067852103",
        Close_ico = "rbxassetid://132966276978826",
        Frame_ico = "rbxassetid://109429151935511",
        Shop_BACKGROUND ="rbxassetid://102151919452993",
        Pointer_ico = "rbxassetid://120202628835237",
        Gacha_Glow = "rbxassetid://6014264734",
        Del_ico = "rbxassetid://119915056737118",
        Move_ico = "rbxassetid://77744554248158",
        Rotate_ico = "rbxassetid://119430934163312",
        Pet_ico = "rbxassetid://87317325041654",
        Decoration_ico = "rbxassetid://105940117361584",
        Confirm_ico = "rbxassetid://140107141846094",
        -- Gameplay & Items
		Coin_ico = "rbxassetid://120673611252447",
        Coin1_ico = "rbxassetid://92342444032080",
        Fish_ico = "rbxassetid://103155001392232",
        Egg_ico = "rbxassetid://70688476970062",
        Food_ico = "rbxassetid://102283947004834",
        
    },

    Models = {
        -- Fish
        GUPPY = "Guppy",
        PIRANHA = "Piranha",
        GENTONG = "Gentong",
        GOLDFISH = "Goldfish",

        -- NPC
        GEROBAK = "M_NPC/Gerobak",
        NELAYAN = "M_NPC/Nelayan",
        PERAHU_SHOP = "M_NPC/Perahu_shop", -- INI YANG BARU

        -- Aquarium
        AQUARIUM_LV1 = "M_Aquarium/Aquarium_Lv1",
        AQUARIUM_LV2 = "M_Aquarium/Aquarium_Lv2",
        AQUARIUM_LV3 = "M_Aquarium/Aquarium_Lv3",

        -- Item
        COIN = "M_Item/Coin",
        COIN1 = "M_Item/Coin1",

        
        -- Egg
        Biasa = "M_Egg/Biasa",
        Langka = "M_Egg/Langka",
        Epik = "M_Egg/Epik",
        
        -- Food
        Pellet1 = "M_Food/Pellet1",
        Pill1 = "M_Food/Pill1",
        Pill2 = "M_Food/Pill2",
        Worm1 = "M_Food/Worm1",
        Worm2 = "M_Food/Worm2",
        Worm3 = "M_Food/Worm3",
        Worm4 = "M_Food/Worm4",
        
        -- Pet
        Crab = "M_Pet/Crab",
        Jellyfish = "M_Pet/Jellyfish",
        Snail1 = "M_Pet/Snail1",

        -- Decoration
        Coral1 = "M_Decoration/Coral1",
        Coral2 = "M_Decoration/Coral2",
        Coral3 = "M_Decoration/Coral3",
        Coral4 = "M_Decoration/Coral4",
        Coral5 = "M_Decoration/Coral5",
        Coral6 = "M_Decoration/Coral6",
        Coral7 = "M_Decoration/Coral7",
        Coral8 = "M_Decoration/Coral8",
        Coral9 = "M_Decoration/Coral9",
        Coral10 = "M_Decoration/Coral10",
        Coral11 = "M_Decoration/Coral11",
        Coral12 = "M_Decoration/Coral12",
        Coral13 = "M_Decoration/Coral13",
        Coral14 = "M_Decoration/Coral14",
        Coral15 = "M_Decoration/Coral15",
        Coral16 = "M_Decoration/Coral16",

        
    }
}
