--!native
--[[
	Asset Configuration Data
	This file is a direct copy of asset_config.luau to bypass a file-syncing issue.
]]
return {
	Images = {
		Frame_ico = "rbxassetid://108110941590961",
		Fish_ico = "rbxassetid://121570342897008",
		Menu_ico = "rbxassetid://113810153703499",
		Coin_ico = "rbxassetid://104704764838778",
		Coin1_ico = "rbxassetid://90895570587188",
		Close_ico = "rbxassetid://102155478970611",
	},
	Sounds = {
		FISH_SPAWN = { id = "rbxassetid://2539296793", volume = 1.2, looped = true },
		FISH_DEATH = { id = "rbxassetid://3853659609", volume = 0.6, looped = true },
		FISH_EAT = { id = "rbxassetid://9114890978", volume = 0.4, looped = true },
		FISH_COIN = { id = "rbxassetid://6817149233", volume = 0.6, looped = true },
		GACHA_ROLL = { id = "rbxassetid://4611822112", volume = 0.6, looped = true },
		GACHA_WIN = { id = "rbxassetid://1846266692", volume = 0.8, looped = false },
		BUTTON_CLICK = { id = "rbxassetid://6042053626", volume = 0.4, looped = false },
		OPEN_AQUARIUM = { id = "rbxassetid://17208204604", volume = 0.8, looped = false },
		DEFAULT_BACKGROUND = { id = "rbxassetid://119240016269232", volume = 0.8, looped = false },
		BUBBLE = { id = "rbxassetid://5217769815", volume = 0.2, looped = false },
		BOSS_CLICK = { id = "rbxassetid://6323775059", volume = 0.6, looped = false },
		BOSS_WARNING = { id = "rbxassetid://7084812679", volume = 1, looped = false },
		BOSS_FIGHTING = { id = "rbxassetid://1839549376", volume = 0.8, looped = false },
		BOSS_EAT = { id = "rbxassetid://625712280", volume = 0.8, looped = false },
		BOSS_SPAWN = { id = "rbxassetid://9114038441", volume = 0.8, looped = false },
		BONUS_TIME_CD = { id = "rbxassetid://6238869231", volume = 0.8, looped = false },
		BONUS_TIME = { id = "rbxassetid://1847548665", volume = 0.8, looped = false },
		BONUS_CLICK = { id = "rbxassetid://18913132985", volume = 1.5, looped = false },
		BONUS_CLICK_EGG = { id = "rbxassetid://289824844", volume = 1.5, looped = false },
		BONUS_RESULT = { id = "rbxassetid://5425356610", volume = 2, looped = false },
		FOOD_DROP = { id = "rbxassetid://3773015931", volume = 1, looped = false },
	},
	Decals = {},
	Animations = {}
}
