return {
    Sounds = {
        UI_HOVER = "rbxassetid://9119532144",
        UI_CLICK = "rbxassetid://9119531818",
        UI_TOAST = "rbxassetid://9119532375",
        CASH_OUT = "rbxassetid://10672658824",
    },

    Images = {
        -- UI Core
        DEFAULT_BACKGROUND = "rbxassetid://10672535737",
        Menu_ico = "rbxassetid://79113340093791",
        Admin_ico = "rbxassetid://80033067852103",
        Close_ico = "rbxassetid://132966276978826",
        Frame_ico = "rbxassetid://109429151935511",

        -- Gameplay & Items
		Coin_ico = "rbxassetid://120673611252447",
        Coin1_ico = "rbxassetid://92342444032080",
        Fish_ico = "rbxassetid://103155001392232",
        
    },

    Models = {
        -- Fish
        GUPPY = "Guppy",
        PIRANHA = "Piranha",
        GENTONG = "Gentong",
        GOLDFISH = "Goldfish",

        -- NPC
        GEROBAK = "M_NPC/Gerobak",
        NELAYAN = "M_NPC/Nelayan",
        PERAHU_SHOP = "M_NPC/Perahu_shop", -- INI YANG BARU

        -- Aquarium
        AQUARIUM_LV1 = "M_Aquarium/Aquarium_Lv1",
        AQUARIUM_LV2 = "M_Aquarium/Aquarium_Lv2",
        AQUARIUM_LV3 = "M_Aquarium/Aquarium_Lv3",

        -- Item
        COIN = "M_Item/Coin",
        COIN1 = "M_Item/Coin1",
    },

    Game = {
        -- Fish Store
        SHOP_ITEM_1 = { id = "rbxassetid://10676998516", price = 100 },
        SHOP_ITEM_2 = { id = "rbxassetid://10677189255", price = 250 },
        SHOP_ITEM_3 = { id = "rbxassetid://5073599420", price = 500 },

        -- Decorations
        DECOR_1 = { id = "rbxassetid://10676998516" },
        DECOR_2 = { id = "rbxassetid://10677189255" },

        -- Effects
        EFFECT_SPAWN = { id = "rbxassetid://5073599420" }
    },
}
